FROM golang:1.23.2 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN go build -o engagement ./services/engagement

FROM debian:12-slim

WORKDIR /app

COPY --from=builder /app/engagement ./engagement

EXPOSE 8090

CMD ["./engagement"]